export const PageDummyData = 
    {
        "success": true,
        "data": [
          {
            "createdName": null,
            "modifiedName": null,
            "id": 38,
            "title": "Bauer Collection",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Bauer-Collection",
            "topicTitle": "Bauer Apparel and Custom Sportswear Brands - Corporate Gear",
            "metaDescription": "Embroidered Bauer apparel is one of the top selling brands for custom sportswear. At Corporate Gear, easily order and customize. Precise customization.",
            "metaKeywords": "Branded t-shirt, BAUER custom, BAUER hats, BAUER hoodie, company sweatshirts, BAUER brand, branded custom sportswear, BAUER hockey jacket, corporate logo apparel, company clothing",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": '2023-01-13T05:06:26',
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": 'Vikas',
            "updatedBy": 'Vikas',
            "status": "P",
            "createdAt": '2023-01-13T05:06:26',
            "updatedAT": '2023-01-13T05:06:26',
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 39,
            "title": "Custom Bella And Canvas Apparel",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Custom-Bella-And-Canvas-Apparel",
            "topicTitle": "Custom BELLA + CANVAS – Corporate Gear",
            "metaDescription": "Create the custom look you want with BELLA + CANVAS apparel. Choose from ultra-soft T-shirts and sweatshirts. Get the Size, Color & Style You Need!",
            "metaKeywords": "bella + canvas, bella canvas tees, bella canvas hoodie, bella canvas full zip hoodie, custom t shirts with company logo, custom bella canvas shirts, bella+canvas shirts, bella and canvas, bella+canvas, bella canvas t shirt, bella canvas tshirts",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 40,
            "title": "Berne Apparel Collection",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Berne-Apparel-Collection",
            "topicTitle": "Custom Berne Clothing for Your Logo – Corporate Gear",
            "metaDescription": "Customize Berne apparel, jackets and custom hats. In-house customization with fast turn times, excellent service.",
            "metaKeywords": "Berne work wear, custom work wear, Berne jackets, Berne t-shirts, custom company apparel, Berne coat, custom work jacket, Berne vest,",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 41,
            "title": "Brumate Collection",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Brumate-Collection",
            "topicTitle": "BruMate Insulated Custom Tumblers – Corporate Gear",
            "metaDescription": "BruMate insulated custom tumblers, mugs, and canteens with your brand logo. Quality corporate gifts they’ll love. Fast turn times.",
            "metaKeywords": "Customized tumblers, customized drinkware, tumblers custom, Br&#252;Mate wine gift set, Br&#252;Mate tumbler, engraved Br&#252;Mate",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 42,
            "title": "Callaway Custom Polo Shirts With Logo",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Callaway-Custom-Polo-Shirts-With-Logo",
            "topicTitle": "Custom Callaway Golf Gear & Polos – Corporate Gear",
            "metaDescription": "Custom Callaway golf gear, balls, polos and logo bags. Personalized or customized with your brand logo. Superior customization. Easy online ordering.",
            "metaKeywords": "Callaway, Callaway golf bags, Callaway duffle, Callaway dri-fit polo, Callaway super soft golf balls, Callaway golf hat, custom Callaway bag, Callaway hats, custom golf balls, custom embroidered apparel",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 43,
            "title": "Custom Camelbak Drinkware And Gear",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Custom-Camelbak-Drinkware-And-Gear",
            "topicTitle": "Custom CamelBak Logo Drinkware – Corporate Gear",
            "metaDescription": "Order all things custom CamelBak! Engrave your logo on custom water bottles, custom tumblers and more. Large inventory and superior customization.",
            "metaKeywords": "Custom camelbak, custom water bottles, custom made tumblers, company logo water bottles, customized drinkware, branded camelbak, camelbak, camelbak water bottle, custom tumblers, customized tumblers, custom water bottle, custom drinkware",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 44,
            "title": "Custom Carhartt Company Clothing",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Custom-Carhartt-Company-Clothing",
            "topicTitle": "Carhartt Customized with Your Company Logo – Corporate Gear",
            "metaDescription": "Custom Carhartt jackets, hoodies, beanies, and bags for your custom embroidered logo. Quick turn time.",
            "metaKeywords": "Custom Carhartt hoodie, custom Carhartt beanie, company clothing, Custom Carhartt jackets, custom company clothing, personalized jackets, custom Carhartt shirts, custom work shirt",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 45,
            "title": "Charles River Apparel Collection",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Charles-River-Apparel-Collection",
            "topicTitle": "Charles River Superior Customization - Corporate Gear",
            "metaDescription": "Custom Charles River Apparel. Superior customization and full-service support.",
            "metaKeywords": "Charles River apparel jacket, business jacket with logo, custom pullovers, Charles River vest, company t-shirts, custom logo jackets, custom jackets with logo, custom pullover, custom polos",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 46,
            "title": "Columbia Collection",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Columbia-Collection",
            "topicTitle": "Custom Columbia Apparel & Backpacks – Corporate Gear",
            "metaDescription": "Customize Columbia backpacks, puffer jackets, hats and corporate clothes for your logo. Easy online ordering, superior customization.",
            "metaKeywords": "custom Columbia jacket, company jackets with logo, Columbia jackets for women, Columbia jackets for men, Columbia shirts custom logo, Columbia vest",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 47,
            "title": "Custom Core365",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Custom-Core365",
            "topicTitle": "Custom Core365 Jackets and Vests - Corporate Gear",
            "metaDescription": "Custom Core365 jackets and vests are an effective way to increase brand awareness. Add Core 365 clothing to your marketing portfolio!",
            "metaKeywords": "custom jackets with logo, custom jackets, custom jacket, customized jacket, custom vest, custom vests, custom embroidered jackets, core 365, core 365 jacket, custom fleece jacket, core 365 vest, core 365 clothing, custom embroidered vest",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 48,
            "title": "Custom Corkcicle Drinkware",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Custom-Corkcicle-Drinkware",
            "topicTitle": "Corkcicle Custom Drinkware – Corporate Gear",
            "metaDescription": "Customizable drinkware. Give the gift of your corporate logo on premium drinkware. Easy online ordering, fast turn times.",
            "metaKeywords": "Corkcicle cup, custom made tumblers, customizable drinkware, promotional drinkware, custom tumblers, Corkcicle tumbler",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 49,
            "title": "Custom Cross Pens And Notebooks",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Custom-Cross-Pens-And-Notebooks",
            "topicTitle": "Custom Cross Pens and Office Supplies – Corporate Gear",
            "metaDescription": "Order custom Cross pens and notebooks to celebrate company events and milestones. Gain access to more inventory and superior customization.",
            "metaKeywords": "Cross pens, custom notebooks, custom business pens, custom logo notebooks, cross office supplies, cross pen, customized pens, custom pen, custom stationary, custom pens with logo, cross ballpoint pen, customize pens, pens customized, cross pen set",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 50,
            "title": "Eddie Bauer Collection",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Eddie-Bauer-Collection",
            "topicTitle": "Custom Eddie Bauer Jackets & Clothing – Corporate Gear",
            "metaDescription": "Customize Eddie Bauer jackets, clothing, and Eddie Bauer duffle bags with your company logo. Easy ordering, helpful service, the results you want!",
            "metaKeywords": "ustom embroidered clothing, Eddie Bauer coats, Eddie Bauer custom fleece jacket, custom Eddie Bauer jackets, Eddie Bauer shirts, Eddie Bauer women’s, Eddie Bauer women’s jacket, Eddie Bauer men’s jacket, Eddie Bauer rain jacket, corporate apparel",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 51,
            "title": "Custom Ember Drinkware",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Custom-Ember-Drinkware",
            "topicTitle": "Custom Ember Smart Mugs – Corporate Gear",
            "metaDescription": "Ember smart mugs are self-heating to keep your beverage piping hot. Superior laser engraving and easy online ordering for your office gifts.",
            "metaKeywords": "Custom travel mugs, laser engraving, custom drinkware, ember 14oz mug, custom logo mugs, ember heated mug, ember Travel Mugs",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 52,
            "title": "Custom Faherty Clothes",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Custom-Faherty-Clothes",
            "topicTitle": "Custom Faherty Clothes – Corporate Gear",
            "metaDescription": "Customize Faherty clothes for a casual &amp; stylish laid-back corporate look. Jumpstart your custom clothing with Faherty Brand sweatshirts, polos and shirts.",
            "metaKeywords": "Faherty clothes, custom polos, custom hoodies for men, Faherty clothing, customized sweatshirts, custom polo shirts, custom sweatshirt, Faherty shirt, Faherty sweatshirt, Faherty hoodie, Faherty logo, Faherty apparel, Faherty clothing brand",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 53,
            "title": "Fairway And Greene Embroidered Polo Shirts",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Fairway-And-Greene-Embroidered-Polo-Shirts",
            "topicTitle": "Fairway & Greene Corporate Golf Wear - Corporate Gear",
            "metaDescription": "Fairway and Greene personalized golf shirts bring distinguished quality to your corporate and golf wear. Superior custom embroidery on custom golf polos.",
            "metaKeywords": "Custom polo shirts with logo, custom vest, fairway and greene ladies, custom embroidered polos, custom golf polos, personalized polos shirts, custom golf shirt, golf shirts custom, customize polos shirts, corporate clothing",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 54,
            "title": "Custom Flexfit Hats",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Custom-Flexfit-Hats",
            "topicTitle": "Flexfit Hats Branded with Your Logo – Corporate Gear",
            "metaDescription": "Custom Flexfit hats are an effective way to increase brand engagement. Order custom logo hats for company gifts and promotional giveaways.",
            "metaKeywords": "custom flexfit hats, custom hats, flexfit hats, custom fitted hats, customizable flexfit hats, custom embroidered hats, customized hats, flexfit, flexfit hat, custom hats embroidered, custom logo hats, flexfit cap, company logo hats, flexfit caps",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 55,
            "title": "Footjoy Collection",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Footjoy-Collection",
            "topicTitle": "FootJoy Custom Polos & Apparel – Corporate Gear",
            "metaDescription": "Order Now - 3-5 week delivery. Custom FootJoy golf polos, quarter zips and apparel for your company logo. In-house customization. Easy ordering, fast service.",
            "metaKeywords": "",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 56,
            "title": "Galvin Green Custom Golf Apparel",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Galvin-Green-Custom-Golf-Apparel",
            "topicTitle": "Custom Galvin Green Golf Apparel | Corporate Gear",
            "metaDescription": "Shop and customize Galvin Green golf apparel and gear. Custom embroidered polos, custom jackets and more for your brand logo!",
            "metaKeywords": "",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 57,
            "title": "Helly Hansen Logo Apparel Collection",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Helly-Hansen-Logo-Apparel-Collection",
            "topicTitle": "Custom Helly Hansen Jackets & Apparel – Corporate Gear",
            "metaDescription": "Easily customize popular Helly Hansen workwear, jackets, and rain gear with your company logo. Excellent inventory, customer support, and results.",
            "metaKeywords": "",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 58,
            "title": "Privacy Policy",
            "pageType": "Website",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "privacy-policy",
            "topicTitle": "Privacy Policy - Is Corporate Gear Legit, The Answer is Yes!",
            "metaDescription": "Is Corporate Gear Legit? Yes! And we take your privacy very seriously. Shop CG to Customize Your Favorite Brands.",
            "metaKeywords": "is corporate gear legit",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "A",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 59,
            "title": "Customize High Sierra Brand",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Customize-High-Sierra-Brand",
            "topicTitle": "Custom High Sierra Brand Accessories – Corporate Gear",
            "metaDescription": "Customize High Sierra brand accessories to turn up the volume on your company gifts with custom speakers and let your logo chill on custom coolers.",
            "metaKeywords": "",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 60,
            "title": "Custom Igloo Coolers And Bags",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Custom-Igloo-Coolers-And-Bags",
            "topicTitle": "Custom Igloo Cooler and Bags- Corporate Gear",
            "metaDescription": "An Igloo cooler personalized with your logo is perfect for promotional events and corporate gifts. Easy online ordering and fast turnaround times.",
            "metaKeywords": "",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 61,
            "title": "Johnnie O Custom Apparel Collection",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Johnnie-O-Custom-Apparel-Collection",
            "topicTitle": "johnnie-O Clothing & Custom Apparel – Corporate Gear",
            "metaDescription": "Classic johnnie-O custom clothing for your corporate apparel. Official partners, easy online ordering, and superior customization",
            "metaKeywords": "",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 62,
            "title": "Klean Kanteen Logo Drinkware",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Klean-Kanteen-Logo-Drinkware",
            "topicTitle": "Klean Kanteen Logo Drinkware – Corporate Gear",
            "metaDescription": "Order Klean Kanteen logo drinkware to promote your brand! Gain access to better inventory and superior customization at Corporate Gear.",
            "metaKeywords": "",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 63,
            "title": "Custom Knack Bags And Backpacks",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Custom-Knack-Bags-And-Backpacks",
            "topicTitle": "KNACK Bags with your Custom Logo – Corporate Gear",
            "metaDescription": "Custom Knack bags are popular employee travel bags for your custom embroidered or printed logo. Excellent service and customization.",
            "metaKeywords": "",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 64,
            "title": "Lacoste Collection",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Lacoste-Collection",
            "topicTitle": "Lacoste Custom Premium Clothing - Corporate Gear",
            "metaDescription": "Customize your logo on Lacoste shirts, polos, hats and tees for premium branded apparel. Easy ordering, superior customizing.",
            "metaKeywords": "",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 65,
            "title": "Custom Linksoul Golf Apparel",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Custom-Linksoul-Golf-Apparel",
            "topicTitle": "Custom Linksoul Golf Apparel and Gear – Corporate Gear",
            "metaDescription": "Customize Linksoul for well-crafted and super comfortable company apparel. Gain access to better inventory and superior customization at Corporate Gear.",
            "metaKeywords": "",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 66,
            "title": "Marine Layer Custom Logo Apparel",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Marine-Layer-Custom-Logo-Apparel",
            "topicTitle": "Custom Embroidered Marine Layer Apparel | Corporate Gear",
            "metaDescription": "Customize your logo on Marine Layer corporate apparel. Ultra-soft fabric and laid-back style! On-site customization, superior service.",
            "metaKeywords": "",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 67,
            "title": "Marmot Custom Logo Jackets And Company Apparel Collection",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Marmot-Custom-Logo-Jackets-And-Company-Apparel-Collection",
            "topicTitle": "Custom Marmot Apparel &amp; Backpacks– Corporate Gear",
            "metaDescription": "Customize Marmot backpacks, puffer jackets, hats and corporate clothes for your logo. Easy online ordering, superior customization.",
            "metaKeywords": "custom clothing, Marmot sweatshirt, custom pullovers, logo Custom jacket, custom embroidery, Marmot vest women’s, Marmot vest men’s, Marmot women’s jacket, Marmot men’s jacket, Marmot puffer vest",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 68,
            "title": "Custom Matouk Gifts And Accessories",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Custom-Matouk-Gifts-And-Accessories",
            "topicTitle": "Custom Matouk Luxury Gifts – Corporate Gear",
            "metaDescription": "Matouk luxury gifts give you the brand level-up you’re after. Order Matouk custom beach towels, personalized robes and custom throw blankets today.",
            "metaKeywords": "",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 69,
            "title": "New Era Custom Hats Apparel",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "New-Era-Custom-Hats-Apparel",
            "topicTitle": "New Era Custom Hats and Apparel – Corporate Gear",
            "metaDescription": "New Era custom hats and apparel for casual office wear, custom branded hats, and quality promotional swag Superior customization and turnaround times.",
            "metaKeywords": "",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 70,
            "title": "Custom Next Level Apparel And Clothing",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Custom-Next-Level-Apparel-And-Clothing",
            "topicTitle": "Next Level Co-Branded Apparel - Corporate Gear",
            "metaDescription": "Shop and customize Next Level for your company. Top quality clothing and apparel ensures your custom printed logo looks professional.",
            "metaKeywords": "next level, next level apparel, logo t shirt, next level tees, next level t shirt, branded t shirts, company tshirts, company logo t shirts, next level apparel t shirts, best custom tshirt, company tee shirts, company t-shirts, next level sweatshirt",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 71,
            "title": "Custom Nike Company Apparel Collection",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Custom-Nike-Company-Apparel-Collection",
            "topicTitle": "Custom Nike (Everything) with your company logo. Nike company apparel",
            "metaDescription": "Order Now - 3-5 week delivery. Custom Nike apparel and gear, personalized, or custom Nike golf shirt and more. Easy ordering, fast service.",
            "metaKeywords": "nike golf shirts, custom nike shirts, nike golf polo shirts, customized nike backpacks, custom nike clothes, custom nike clothing, custom nike dri fit shirts, custom nike polo, custom nike t shirts, custom nike polo shirts, custom nike apparel",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 72,
            "title": "Ogio Collection",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Ogio-Collection",
            "topicTitle": "Custom OGIO Backpacks, Golf bags, Polos – Corporate Gear",
            "metaDescription": "Custom OGIO backpacks, golf bags, bags, and apparel to boost your brand logo. Dedicated account service and excellent results.",
            "metaKeywords": "Custom polo shirts, custom golf bags, OGIO clothing, custom OGIO backpacks, custom jacket, custom bags, OGIO cooler, OGIO logo, OGIO logo custom backpack, OGIO custom golf bags",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          },
          {
            "createdName": null,
            "modifiedName": null,
            "id": 73,
            "title": "Peter Millar Collection",
            "pageType": "Landing",
            "passRequired": null,
            "password": "",
            "passExpiryPeriod": null,
            "tag": "",
            "author": "",
            "previewAs": "",
            "storeId": 1,
            "slug": "Peter-Millar-Collection",
            "topicTitle": "Custom Peter Millar Shirts, Jackets - Corporate Gear",
            "metaDescription": "Customize with an official Peter Millar brand partner. Excellent customization and order experience. Customize golf shirts, quarter zips, jackets & gear.",
            "metaKeywords": "peter millar golf, customized golf shirts, corporate gifting, custom golf gifts, polo shirts with logo, peter millar polos, peter millar quarter zips, personalized golf shirts, customizable golf shirts, peter millar men’s shirts, customized golf polo",
            "templateId": 0,
            "headHtml": "",
            "footerhtml": "",
            "canonicalurl": "",
            "publishDuration": null,
            "publishDate": null,
            "publishTime": null,
            "unpublishDate": null,
            "unpublishTime": null,
            "scheduleUnpublish": null,
            "redirectPageId": null,
            "createdBy": null,
            "updatedBy": null,
            "status": "P",
            "createdAt": null,
            "updatedAT": null,
            "isHomePage": null,
            "publish_status": null,
            "menuType": null,
            "oldId": null,
            "storiesImage": null,
            "categoryId": 0,
            "displaySideBar": null,
            "description": null
          }
        ],
        "errors": {},
        "otherData": null
      }
